title: 'Hi ðŸ‘‹, Call me TJ'
description: 'alias Teja.. Rahul Teja ðŸ˜Ž'
# logo: /Users/rahulteja/Downloads/pro_pic2.jpeg
logo: <img src="/Users/rahulteja/Downloads/pro_pic2.jpeg" alt="lasagna">
#description: text below image
#description: text below image
# show_downloads: true
theme: jekyll-theme-merlot
